super-simple .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,60 +24,61 @@ before_install:
  - tar xvf petsc-lite-3.6.2.tar.gz
  - cd petsc-3.6.2
  - ./configure --with-cc=gcc --with-cxx=g++ --with-fc=gfortran --download-fblaslapack --download-mpich
-
- - sudo add-apt-repository -y ppa:hvr/ghc
- - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
- - export PATH=/opt/ghc/$GHCVER/bin:$PATH
- - echo "Check version again"
- - ghc   --version
- - cabal --version
+ - cd ../..
+ # - sudo add-apt-repository -y ppa:hvr/ghc
+ # - travis_retry sudo apt-get update
+ # - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
+ # - export PATH=/opt/ghc/$GHCVER/bin:$PATH
+ # - echo "Check version again"
+ # - ghc   --version
+ # - cabal --version
 
 cache:
   directories:
   - petsc
 
 install:
-  - travis_retry cabal-$CABALVER install --only-dependencies --force-reinstalls --enable-tests
-  #- travis_retry cabal-$CABALVER install --only-dependencies --force-reinstalls --enable-tests ${COVOPT}
+  # - travis_retry cabal-$CABALVER install --only-dependencies --force-reinstalls --enable-tests
+  # #- travis_retry cabal-$CABALVER install --only-dependencies --force-reinstalls --enable-tests ${COVOPT}
 
 #script:
 # - bash testit.sh
 # - echo "All done."
 
 script:
-  # -v2 provides useful information for debugging
-  #- cabal-$CABALVER configure --enable-tests ${COVOPT} --enable-benchmarks -v2
-  - cabal-$CABALVER configure --enable-tests --enable-benchmarks -v2
+  - make
+  # # -v2 provides useful information for debugging
+  # #- cabal-$CABALVER configure --enable-tests ${COVOPT} --enable-benchmarks -v2
+  # - cabal-$CABALVER configure --enable-tests --enable-benchmarks -v2
 
-  # this builds all libraries and executables
-  # (including tests/benchmarks)
-  - cabal-$CABALVER build
-  - find . -iname '*.tix'
-  - find . -iname '*.mix'
+  # # this builds all libraries and executables
+  # # (including tests/benchmarks)
+  # - cabal-$CABALVER build
+  # - find . -iname '*.tix'
+  # - find . -iname '*.mix'
 
-  #- cabal-$CABALVER test --keep-tix-files
-  - cabal-$CABALVER test
-  - find . -iname '*.tix'
+  # #- cabal-$CABALVER test --keep-tix-files
+  # - cabal-$CABALVER test
+  # - find . -iname '*.tix'
 
-  - bash testit.sh
-  - echo "Unit tests successful!"
+  # - bash testit.sh
+  # - echo "Unit tests successful!"
 
-  - cabal-$CABALVER check
+  # - cabal-$CABALVER check
 
-  # tests that a source-distribution can be generated
-  - cabal-$CABALVER sdist
+  # # tests that a source-distribution can be generated
+  # - cabal-$CABALVER sdist
 
-  # check that the generated source-distribution can be built & installed
-  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
-    cd dist/;
-    if [ -f "$SRC_TGZ" ]; then
-       cabal install "$SRC_TGZ";
-    else
-       echo "expected '$SRC_TGZ' not found";
-       exit 1;
-    fi
-  - echo ${PWD}
+  # # check that the generated source-distribution can be built & installed
+  # - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}') ;
+  #   cd dist/;
+  #   if [ -f "$SRC_TGZ" ]; then
+  #      cabal install "$SRC_TGZ";
+  #   else
+  #      echo "expected '$SRC_TGZ' not found";
+  #      exit 1;
+  #   fi
+  # - echo ${PWD}
 
 #after_script:
 #  - echo ${PWD}
